c This file contains the shortest path results for given pairs
c Generated by normal_dijkstra.cpp
c -------------------------------------------
p res sp ss karol
f ./input/duze_dane.gr ./input/pary.p2p
g 5000 50000 1 1000
c -------------------------------------------
d 1 5 398
d 5 1 943
d 1 2 343
