c This file contains the shortest path results for given sources
c Generated by normal_dijkstra.cpp
c -------------------------------------------
p res sp ss karol
f ./input/duze_dane.gr ./input/zrodla.ss
g 5000 50000 1 1000
c -------------------------------------------
t 1
