c This file contains the shortest path results
c Generated by normal_dijkstra.cpp
c -------------------------------------------
p res sp ss karol
f duze_dane.gr zrodla.ss
g 500000 1000000 1 1000
c -------------------------------------------
t 107.533
